include_well_known_types: false
srcs_dir: ./src
srcs:
  - test.proto
  - package.proto
  - deep/deep.proto
output:
  - js: dist/web
  - ts:
      dir: dist/web
      service: true
  - js: dist/node
  - ts: dist/node
  - ngx: dist/ngx
