include_well_known_types: false
srcs_dir: ./src
srcs:
  - test.proto
  - package.proto
  - deep/deep.proto
output:
  - js:
      dir: dist/node
      options:
        import_style: commonjs
        binary: true
  - ts: dist/node
  - grpc-node:
      dir: dist/node
      custom: true
      plugin: grpc_tools_node_protoc_plugin
  - js:
      dir: dist/web
      options:
        import_style: commonjs
        binary: true
  - ts:
      dir: dist/web
      options:
        service: true
