srcs_dir: ./src
srcs:
  - test.proto
  - package.proto
  - deep/deep.proto
output:

  # Node.js with .d.ts for message typpes
  - js:
      dir: dist/node
      options:
        import_style: commonjs
        binary: true
  - ts: dist/node

  # gprc service files (no service .d.ts files)
  - grpc-node:
      dir: dist/node
      custom: true
      plugin: grpc_tools_node_protoc_plugin
  
  # web output from https://github.com/improbable-eng/ts-protoc-gen
  - js:
      dir: dist/improbable-eng-web
      options:
        import_style: commonjs
        binary: true
  - ts:
      dir: dist/improbable-eng-web
      options:
        service: true

  # official grpc-web output
  - grpc-web:
      dir: dist/grpc-web
      options:
        mode: base64

  # Built in languages with default options
  - cpp: dist/cpp
  - csharp: dist/csharp
  - java: dist/java
  - objc: dist/objc
  - python: dist/python
  - ruby: dist/ruby
  - php: dist/php
